//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farming.WpfClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logi
    {
        public int id_event { get; set; }
        public string tab { get; set; }
        public int id { get; set; }
        public string @event { get; set; }
        public System.DateTime date { get; set; }
    }
}
